from django.contrib import admin
from django.urls import path, include
from usuarios.views import (
    ColegioListCreateView,
    ColegioDetailView,
    ColegioAdministradoresView,
    SedeListCreateView,
    SedeDetailView,
    EstudianteListCreateView,
    EstudianteDetailView,
    EstudianteFotoView,
    EstudianteSinAsignarListView,
    ConductorListCreateView,
    ConductorDetailView,
    ConductorEstudiantesListView,
    ConductorAsignarEstudiantesView,
    ConductorDesasignarEstudianteView,
    ApoderadoListCreateView,
    ApoderadoDetailView,
    CambiarPasswordView,
    DelegadoEstudiantesListView,
    DelegadoPerfilView,
    DelegadoAdminListCreateView,
    DelegadoAdminDetailView,
    DelegadoDesvincularEstudianteView,
    DashboardStatsView,
    RegistrarFCMTokenView,
    NotificacionListView,
    MarcarNotificacionLeidaView,
    MarcarTodasNotificacionesLeidasView,
    EliminarNotificacionView,
    EliminarTodasNotificacionesView,
    RutaIniciarView,
    RutaEscanearQRView,
    RutaEscaneoFacialView,
    RutaConsultarQREntregaView,
    RutaConfirmarEntregaMultipleView,
    RegistrarRostroView,
    RutaFinalizarView,
    EmergenciaCrearView,
    AvisoSistemaView,
    FurgonListCreateView,
    FurgonDetailView,
    RutaListCreateView,
    RutaDetailView,
    SeguimientoView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('usuarios.urls')),

    # Seguimiento GPS & En tiempo real
    path('api/seguimiento/', SeguimientoView.as_view(), name='seguimiento'),

    # Colegios & Sedes
    path('api/colegios/', ColegioListCreateView.as_view(), name='colegios-list-create'),
    path('api/colegios/<int:pk>/', ColegioDetailView.as_view(), name='colegio-detail'),
    path('api/colegios/<int:colegio_id>/administradores/', ColegioAdministradoresView.as_view(), name='colegio-administradores'),
    path('api/colegios/<int:colegio_id>/sedes/', SedeListCreateView.as_view(), name='sedes-list-create'),
    path('api/sedes/<int:pk>/', SedeDetailView.as_view(), name='sede-detail'),
    path('api/estudiantes/', EstudianteListCreateView.as_view(), name='estudiantes-list-create'),
    path('api/estudiantes/sin-asignar/', EstudianteSinAsignarListView.as_view(), name='estudiantes-sin-asignar'),
    path('api/estudiantes/<int:estudiante_id>/', EstudianteDetailView.as_view(), name='estudiante-detail'),
    path('api/estudiantes/<int:estudiante_id>/foto/', EstudianteFotoView.as_view(), name='estudiante-foto'),
    path('api/estudiantes/<int:estudiante_id>/registrar-rostro/', RegistrarRostroView.as_view(), name='estudiante-registrar-rostro'),
    path('api/conductores/', ConductorListCreateView.as_view(), name='conductores-list-create'),
    path('api/conductores/<int:conductor_id>/', ConductorDetailView.as_view(), name='conductor-detail'),
    path('api/conductores/<int:conductor_id>/estudiantes/', ConductorEstudiantesListView.as_view(), name='conductor-estudiantes-list'),
    path('api/conductores/<int:conductor_id>/asignar-estudiantes/', ConductorAsignarEstudiantesView.as_view(), name='conductor-asignar-estudiantes'),
    path('api/conductores/<int:conductor_id>/desasignar-estudiante/', ConductorDesasignarEstudianteView.as_view(), name='conductor-desasignar-estudiante'),
    path('api/apoderados/', ApoderadoListCreateView.as_view(), name='apoderados-list-create'),
    path('api/apoderados/<int:apoderado_id>/', ApoderadoDetailView.as_view(), name='apoderado-detail'),
    path('api/apoderados/<int:apoderado_id>/cambiar-password/', CambiarPasswordView.as_view(), name='apoderado-cambiar-password'),
    path('api/delegados/', DelegadoAdminListCreateView.as_view(), name='delegados-admin-list-create'),
    path('api/delegados/<int:delegado_id>/', DelegadoAdminDetailView.as_view(), name='delegado-admin-detail'),
    path('api/delegados/desvincular-estudiante/', DelegadoDesvincularEstudianteView.as_view(), name='delegado-desvincular-estudiante'),
    path('api/delegados/estudiantes/', DelegadoEstudiantesListView.as_view(), name='delegado-estudiantes-list'),
    path('api/delegados/perfil/', DelegadoPerfilView.as_view(), name='delegado-perfil'),
    path('api/dashboard/stats/', DashboardStatsView.as_view(), name='dashboard-stats'),

    # Furgones & Rutas CRUD
    path('api/furgones/', FurgonListCreateView.as_view(), name='furgones-list-create'),
    path('api/furgones/<int:pk>/', FurgonDetailView.as_view(), name='furgon-detail'),
    path('api/rutas-admin/', RutaListCreateView.as_view(), name='rutas-admin-list-create'),
    path('api/rutas-admin/<int:pk>/', RutaDetailView.as_view(), name='rutas-admin-detail'),

    # Notificaciones & FCM
    path('api/notificaciones/fcm-token/', RegistrarFCMTokenView.as_view(), name='fcm-token-register'),
    path('api/notificaciones/', NotificacionListView.as_view(), name='notificaciones-list'),
    path('api/notificaciones/<int:notificacion_id>/marcar-leido/', MarcarNotificacionLeidaView.as_view(), name='notificacion-marcar-leido'),
    path('api/notificaciones/marcar-todas-leidas/', MarcarTodasNotificacionesLeidasView.as_view(), name='notificaciones-marcar-todas-leidas'),
    path('api/notificaciones/<int:notificacion_id>/eliminar/', EliminarNotificacionView.as_view(), name='notificacion-eliminar'),
    path('api/notificaciones/<int:notificacion_id>/', EliminarNotificacionView.as_view(), name='notificacion-eliminar-directo'),
    path('api/notificaciones/eliminar-todas/', EliminarTodasNotificacionesView.as_view(), name='notificaciones-eliminar-todas'),
    path('api/notificaciones/aviso-sistema/', AvisoSistemaView.as_view(), name='notificaciones-aviso-sistema'),

    # Acciones de Ruta & Emergencias (Generan Push automáticamente)
    path('api/rutas/iniciar/', RutaIniciarView.as_view(), name='rutas-iniciar'),
    path('api/rutas/escanear-qr/', RutaEscanearQRView.as_view(), name='rutas-escanear-qr'),
    path('api/rutas/escaneo-facial/', RutaEscaneoFacialView.as_view(), name='rutas-escaneo-facial'),
    path('api/rutas/consultar-qr-entrega/', RutaConsultarQREntregaView.as_view(), name='rutas-consultar-qr-entrega'),
    path('api/rutas/confirmar-entrega-multiple/', RutaConfirmarEntregaMultipleView.as_view(), name='rutas-confirmar-entrega-multiple'),
    path('api/rutas/finalizar/', RutaFinalizarView.as_view(), name='rutas-finalizar'),
    path('api/emergencias/', EmergenciaCrearView.as_view(), name='emergencias-crear'),
]


