# Generated by Django 6.1 on 2026-08-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('colegio', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('direccion_principal', models.CharField(max_length=255)),
                ('direccion_alternativa', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_autorizada', models.CharField(blank=True, max_length=200, null=True)),
                ('rut_persona_autorizada', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='usuarios.perfilapoderado')),
            ],
        ),
    ]
