# Generated by Django on 2026-08-20

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(
                blank=True,
                help_text='Foto privada del estudiante; nunca se publica como archivo estático.',
                null=True,
                upload_to=usuarios.models.foto_estudiante_upload_to,
            ),
        ),
    ]
