# Generated by Django 6.1 on 2026-08-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_fcmtoken_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_asignados', to='usuarios.perfilconductor'),
        ),
    ]
