# Generated by Django 6.1 on 2026-08-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_estudiante_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furgon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(default=15)),
                ('conductor_asignado', models.CharField(blank=True, default='', max_length=150)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('conductor', models.CharField(blank=True, default='', max_length=150)),
                ('colegio', models.CharField(default='Escuela Bosques del Viento', max_length=200)),
                ('estudiantes_count', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
