# Generated by Django 6.1 on 2026-09-06 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_furgon_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('apoderado', 'Apoderado'), ('conductor', 'Conductor'), ('admin', 'Administrador'), ('delegado', 'Delegado')], default='apoderado', max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilDelegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_delegado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
