# Generated by Django 6.1 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


def migrar_asignaciones_existentes(apps, schema_editor):
    PerfilConductor = apps.get_model('usuarios', 'PerfilConductor')
    Furgon = apps.get_model('usuarios', 'Furgon')

    conductores_por_nombre = {}
    for perfil in PerfilConductor.objects.select_related('usuario'):
        nombre = f'{perfil.usuario.first_name} {perfil.usuario.last_name}'.strip().casefold()
        if nombre:
            conductores_por_nombre[nombre] = perfil

    for furgon in Furgon.objects.exclude(conductor_asignado=''):
        conductor = conductores_por_nombre.get(furgon.conductor_asignado.strip().casefold())
        if conductor:
            conductor.furgon_asignado_id = furgon.id
            conductor.save(update_fields=['furgon_asignado'])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_rol_perfildelegado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilconductor',
            name='furgon_asignado',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='perfil_conductor_asignado',
                to='usuarios.furgon',
            ),
        ),
        migrations.RunPython(migrar_asignaciones_existentes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='furgon',
            name='conductor_asignado',
        ),
    ]
