# Generated by Django 6.1 on 2026-09-15 23:55

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_rol_perfildelegado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='embedding_facial',
            field=models.JSONField(blank=True, help_text='Vector de características faciales SFace (128 floats)', null=True),
        ),
        migrations.AddField(
            model_name='perfilapoderado',
            name='embedding_facial',
            field=models.JSONField(blank=True, help_text='Vector de características faciales SFace (128 floats)', null=True),
        ),
        migrations.AddField(
            model_name='perfilapoderado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.foto_apoderado_upload_to),
        ),
        migrations.AddField(
            model_name='perfildelegado',
            name='embedding_facial',
            field=models.JSONField(blank=True, help_text='Vector de características faciales SFace (128 floats)', null=True),
        ),
        migrations.AddField(
            model_name='perfildelegado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.foto_delegado_upload_to),
        ),
    ]
