# Generated by Django 6.1 on 2026-09-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_estudiante_embedding_facial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('emergencia_ruta', 'Emergencia en Ruta'), ('emergencia_estudiante', 'Emergencia de Estudiante')], default='emergencia_ruta', max_length=30)),
                ('tipo_emergencia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencias_reportadas', to='usuarios.perfilconductor')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to='usuarios.estudiante')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
