# Generated by Django 6.1 on 2026-09-18 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_emergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rbd', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='colegio',
            new_name='colegio_texto_legacy',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio_texto_legacy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='colegio',
            new_name='colegio_texto_legacy',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='colegio_texto_legacy',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='usuarios.colegio'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='usuarios.colegio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_plataforma', 'Administrador de Plataforma'), ('admin_colegio', 'Administrador de Colegio'), ('apoderado', 'Apoderado'), ('conductor', 'Conductor'), ('admin', 'Administrador'), ('delegado', 'Delegado')], default='apoderado', max_length=30),
        ),
        migrations.AddField(
            model_name='furgon',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furgones', to='usuarios.colegio'),
        ),
        migrations.AddField(
            model_name='perfilapoderado',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoderados', to='usuarios.colegio'),
        ),
        migrations.AddField(
            model_name='perfilconductor',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores', to='usuarios.colegio'),
        ),
        migrations.AddField(
            model_name='perfildelegado',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegados', to='usuarios.colegio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.colegio'),
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='usuarios.colegio')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='usuarios.sede'),
        ),
        migrations.AddField(
            model_name='furgon',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furgones', to='usuarios.sede'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='usuarios.sede'),
        ),
    ]
