# Generated by Antigravity for Multi-Colegio Migration

from django.db import migrations


def migrar_colegios_y_asociar_entidades(apps, schema_editor):
    Colegio = apps.get_model('usuarios', 'Colegio')
    Estudiante = apps.get_model('usuarios', 'Estudiante')
    Ruta = apps.get_model('usuarios', 'Ruta')
    PerfilApoderado = apps.get_model('usuarios', 'PerfilApoderado')
    PerfilConductor = apps.get_model('usuarios', 'PerfilConductor')
    PerfilDelegado = apps.get_model('usuarios', 'PerfilDelegado')
    Furgon = apps.get_model('usuarios', 'Furgon')
    Usuario = apps.get_model('usuarios', 'Usuario')

    # 1. Asegurar que "Escuela Bosques del Viento" exista como registro real de Colegio (Colegio A)
    colegio_escuela_bosques, _ = Colegio.objects.get_or_create(
        nombre="Escuela Bosques del Viento",
        defaults={"activo": True}
    )

    # 2. Recopilar todos los nombres de colegio únicos desde colegio_texto_legacy en Estudiante y Ruta
    nombres_colegios = set()

    for est in Estudiante.objects.all():
        txt = (est.colegio_texto_legacy or '').strip()
        if txt:
            nombres_colegios.add(txt)

    for r in Ruta.objects.all():
        txt = (r.colegio_texto_legacy or '').strip()
        if txt:
            nombres_colegios.add(txt)

    # Crear registros en la tabla Colegio para cada nombre encontrado
    colegios_map = {}
    for nombre in nombres_colegios:
        col_obj, _ = Colegio.objects.get_or_create(
            nombre=nombre,
            defaults={"activo": True}
        )
        colegios_map[nombre] = col_obj

    # 3. Vincular Estudiantes a su colegio_id
    for est in Estudiante.objects.all():
        txt = (est.colegio_texto_legacy or '').strip()
        if txt in colegios_map:
            est.colegio = colegios_map[txt]
            est.save(update_fields=['colegio'])

    # 4. Vincular Rutas a su colegio_id
    for r in Ruta.objects.all():
        txt = (r.colegio_texto_legacy or '').strip()
        if txt in colegios_map:
            r.colegio = colegios_map[txt]
            r.save(update_fields=['colegio'])

    # 5. Vincular PerfilApoderado a su colegio_id (basado en el colegio de sus estudiantes)
    for apoderado in PerfilApoderado.objects.all():
        est = apoderado.estudiantes.filter(colegio__isnull=False).first()
        if est and est.colegio:
            apoderado.colegio = est.colegio
            apoderado.save(update_fields=['colegio'])

    # 6. Vincular PerfilConductor a su colegio_id (basado en sus estudiantes asignados)
    for conductor in PerfilConductor.objects.all():
        est = conductor.estudiantes_asignados.filter(colegio__isnull=False).first()
        if est and est.colegio:
            conductor.colegio = est.colegio
            conductor.save(update_fields=['colegio'])

    # 7. Vincular Furgon a su colegio_id (basado en el conductor asignado si aplica)
    for furgon in Furgon.objects.all():
        if furgon.conductor_asignado:
            cond = PerfilConductor.objects.filter(
                usuario__first_name__icontains=furgon.conductor_asignado,
                colegio__isnull=False
            ).first()
            if cond and cond.colegio:
                furgon.colegio = cond.colegio
                furgon.save(update_fields=['colegio'])

    # 8. Migrar usuarios administradores actuales (rol='admin' o superusuarios) al rol 'admin_plataforma'
    for user in Usuario.objects.all():
        if user.rol in ['admin', 'admin_plataforma'] or user.is_superuser or user.is_staff:
            user.rol = 'admin_plataforma'
            user.save(update_fields=['rol'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_colegio_estudiante_colegio_texto_legacy_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_colegios_y_asociar_entidades, reverse_code=reverse_migration),
    ]
